version: "3"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: md_petshop
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
