// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Cart struct {
	ID string
}

type CartItem struct {
	ID     string
	ItemID string
	Qty    int16
	CartID string
}
